service:
  openweathermap:
    current_weather_data:
      url: https://api.openweathermap.org/data/2.5/
      appid: blabla
      units: metric
      cities:
        - Ottawa,ca
        - New York,us
        - Helsinki,fi
        - London,uk
        - Beirut,lb
        - Singapore,sg
        - Sydney,au
        - Auckland,nz
...
